manifest:
  remotes:
    - name: osmakari
      url-base: https://github.com/osmakari
  projects:
    - name: zmk
      remote: osmakari
      revision: v1.0.1
      import: app/west.yml
  self:
    path: config